# Generated by Django 3.2.7 on 2021-10-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_info', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('age', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('weight', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('bmi', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('employee', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('insurance', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('insurancehist1', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('insurancehist2', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('family_his', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('medical_his', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
            ],
        ),
    ]
