# Generated by Django 3.2 on 2022-04-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211025_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancemodel',
            name='risk_level',
            field=models.IntegerField(default=0),
        ),
    ]
